### ISSUE TITLE
Unable to run locally

### ISSUE THREAD

**Issue by ghost** [vercel-solutions/nextjs-portfolio-starter#18]
Right after cloning from Next website I'm unable to run this locally after running the 'next' command. I've cleaned and reinstalled many different versions of node, react, react-dom to address earlier errors, and below is the latest error that's preventing the project from running locally.

```
 ken@mbp  ~/Documents/GitHub/blog_next main ± next
ready - started server on 0.0.0.0:3000, url: http://localhost:3000
info  - automatically enabled Fast Refresh for 1 custom loader
warn  - Found lockfile missing swc dependencies, patching...
warn  - Lockfile was successfully patched, please run "npm install" to ensure @next/swc dependencies are downloaded
event - compiled client and server successfully in 2.5s (176 modules)
wait  - compiling /_error (client and server)...
event - compiled client and server successfully in 186 ms (177 modules)
Error: Cannot find module 'next/dist/shared/lib/is-plain-object.js'
Require stack:
- /Users/ken/Documents/GitHub/blog_next/.next/server/pages/_document.js
- /Users/ken/.nvm/versions/node/v15.14.0/lib/node_modules/next/dist/server/require.js
- /Users/ken/.nvm/versions/node/v15.14.0/lib/node_modules/next/dist/server/next-server.js
- /Users/ken/.nvm/versions/node/v15.14.0/lib/node_modules/next/dist/server/next.js
- /Users/ken/.nvm/versions/node/v15.14.0/lib/node_modules/next/dist/server/lib/start-server.js
- /Users/ken/.nvm/versions/node/v15.14.0/lib/node_modules/next/dist/cli/next-dev.js
- /Users/ken/.nvm/versions/node/v15.14.0/lib/node_modules/next/dist/bin/next
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:924:15)
    at Function.mod._resolveFilename (/Users/ken/.nvm/versions/node/v15.14.0/lib/node_modules/next/dist/build/webpack/require-hook.js:182:28)
    at Function.Module._load (node:internal/modules/cjs/loader:769:27)
    at Module.require (node:internal/modules/cjs/loader:996:19)
    at require (node:internal/modules/cjs/helpers:92:18)
    at Object.../shared/lib/is-plain-object (/Users/ken/Documents/GitHub/blog_next/.next/server/pages/_document.js:175:18)
    at __webpack_require__ (/Users/ken/Documents/GitHub/blog_next/.next/server/webpack-runtime.js:33:42)
    at eval (webpack-internal:///../../../.nvm/versions/node/v15.14.0/lib/node_modules/next/dist/lib/is-error.js:7:22)
    at Object.../../../.nvm/versions/node/v15.14.0/lib/node_modules/next/dist/lib/is-error.js (/Users/ken/Documents/GitHub/blog_next/.next/server/pages/_document.js:77:1)
    at __webpack_require__ (/Users/ken/Documents/GitHub/blog_next/.next/server/webpack-runtime.js:33:42) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/Users/ken/Documents/GitHub/blog_next/.next/server/pages/_document.js',
    '/Users/ken/.nvm/versions/node/v15.14.0/lib/node_modules/next/dist/server/require.js',
    '/Users/ken/.nvm/versions/node/v15.14.0/lib/node_modules/next/dist/server/next-server.js',
    '/Users/ken/.nvm/versions/node/v15.14.0/lib/node_modules/next/dist/server/next.js',
    '/Users/ken/.nvm/versions/node/v15.14.0/lib/node_modules/next/dist/server/lib/start-server.js',
    '/Users/ken/.nvm/versions/node/v15.14.0/lib/node_modules/next/dist/cli/next-dev.js',
    '/Users/ken/.nvm/versions/node/v15.14.0/lib/node_modules/next/dist/bin/next'
  ]
}
info  - automatically enabled Fast Refresh for 1 custom loader
warn  - Fast Refresh had to perform a full reload. Read more: https://nextjs.org/docs/basic-features/fast-refresh#how-it-works
Error: Failed to fetch update manifest Internal Server Error
    at http://localhost:3000/_next/static/chunks/fallback/webpack.js?ts=1658102626059:1153:37
wait  - compiling / (client and server)...
event - compiled client and server successfully in 2.3s (275 modules)
Error: Cannot find module 'next/dist/shared/lib/is-plain-object.js'
Require stack:
- /Users/ken/Documents/GitHub/blog_next/.next/server/pages/_document.js
- /Users/ken/.nvm/versions/node/v15.14.0/lib/node_modules/next/dist/server/require.js
- /Users/ken/.nvm/versions/node/v15.14.0/lib/node_modules/next/dist/server/next-server.js
- /Users/ken/.nvm/versions/node/v15.14.0/lib/node_modules/next/dist/server/next.js
- /Users/ken/.nvm/versions/node/v15.14.0/lib/node_modules/next/dist/server/lib/start-server.js
- /Users/ken/.nvm/versions/node/v15.14.0/lib/node_modules/next/dist/cli/next-dev.js
- /Users/ken/.nvm/versions/node/v15.14.0/lib/node_modules/next/dist/bin/next
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:924:15)
    at Function.mod._resolveFilename (/Users/ken/.nvm/versions/node/v15.14.0/lib/node_modules/next/dist/build/webpack/require-hook.js:182:28)
    at Function.Module._load (node:internal/modules/cjs/loader:769:27)
    at Module.require (node:internal/modules/cjs/loader:996:19)
    at require (node:internal/modules/cjs/helpers:92:18)
    at Object.../shared/lib/is-plain-object (/Users/ken/Documents/GitHub/blog_next/.next/server/pages/_document.js:175:18)
    at __webpack_require__ (/Users/ken/Documents/GitHub/blog_next/.next/server/webpack-runtime.js:33:42)
    at eval (webpack-internal:///../../../.nvm/versions/node/v15.14.0/lib/node_modules/next/dist/lib/is-error.js:7:22)
    at Object.../../../.nvm/versions/node/v15.14.0/lib/node_modules/next/dist/lib/is-error.js (/Users/ken/Documents/GitHub/blog_next/.next/server/pages/_document.js:77:1)
    at __webpack_require__ (/Users/ken/Documents/GitHub/blog_next/.next/server/webpack-runtime.js:33:42) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/Users/ken/Documents/GitHub/blog_next/.next/server/pages/_document.js',
    '/Users/ken/.nvm/versions/node/v15.14.0/lib/node_modules/next/dist/server/require.js',
    '/Users/ken/.nvm/versions/node/v15.14.0/lib/node_modules/next/dist/server/next-server.js',
    '/Users/ken/.nvm/versions/node/v15.14.0/lib/node_modules/next/dist/server/next.js',
    '/Users/ken/.nvm/versions/node/v15.14.0/lib/node_modules/next/dist/server/lib/start-server.js',
    '/Users/ken/.nvm/versions/node/v15.14.0/lib/node_modules/next/dist/cli/next-dev.js',
    '/Users/ken/.nvm/versions/node/v15.14.0/lib/node_modules/next/dist/bin/next'
  ]
}
error - Error: Cannot find module 'next/dist/shared/lib/is-plain-object.js'
Require stack:
- /Users/ken/Documents/GitHub/blog_next/.next/server/pages/_document.js
- /Users/ken/.nvm/versions/node/v15.14.0/lib/node_modules/next/dist/server/require.js
- /Users/ken/.nvm/versions/node/v15.14.0/lib/node_modules/next/dist/server/next-server.js
- /Users/ken/.nvm/versions/node/v15.14.0/lib/node_modules/next/dist/server/next.js
- /Users/ken/.nvm/versions/node/v15.14.0/lib/node_modules/next/dist/server/lib/start-server.js
- /Users/ken/.nvm/versions/node/v15.14.0/lib/node_modules/next/dist/cli/next-dev.js
- /Users/ken/.nvm/versions/node/v15.14.0/lib/node_modules/next/dist/bin/next
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:924:15)
    at Function.mod._resolveFilename (/Users/ken/.nvm/versions/node/v15.14.0/lib/node_modules/next/dist/build/webpack/require-hook.js:182:28)
    at Function.Module._load (node:internal/modules/cjs/loader:769:27)
    at Module.require (node:internal/modules/cjs/loader:996:19)
    at require (node:internal/modules/cjs/helpers:92:18)
    at Object.../shared/lib/is-plain-object (/Users/ken/Documents/GitHub/blog_next/.next/server/pages/_document.js:175:18)
    at __webpack_require__ (/Users/ken/Documents/GitHub/blog_next/.next/server/webpack-runtime.js:33:42)
    at eval (webpack-internal:///../../../.nvm/versions/node/v15.14.0/lib/node_modules/next/dist/lib/is-error.js:7:22)
    at Object.../../../.nvm/versions/node/v15.14.0/lib/node_modules/next/dist/lib/is-error.js (/Users/ken/Documents/GitHub/blog_next/.next/server/pages/_document.js:77:1)
    at __webpack_require__ (/Users/ken/Documents/GitHub/blog_next/.next/server/webpack-runtime.js:33:42) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/Users/ken/Documents/GitHub/blog_next/.next/server/pages/_document.js',
    '/Users/ken/.nvm/versions/node/v15.14.0/lib/node_modules/next/dist/server/require.js',
    '/Users/ken/.nvm/versions/node/v15.14.0/lib/node_modules/next/dist/server/next-server.js',
    '/Users/ken/.nvm/versions/node/v15.14.0/lib/node_modules/next/dist/server/next.js',
    '/Users/ken/.nvm/versions/node/v15.14.0/lib/node_modules/next/dist/server/lib/start-server.js',
    '/Users/ken/.nvm/versions/node/v15.14.0/lib/node_modules/next/dist/cli/next-dev.js',
    '/Users/ken/.nvm/versions/node/v15.14.0/lib/node_modules/next/dist/bin/next'
  ],
  page: '/'
}
Error: Cannot find module 'next/dist/shared/lib/is-plain-object.js'
Require stack:
- /Users/ken/Documents/GitHub/blog_next/.next/server/pages/_document.js
- /Users/ken/.nvm/versions/node/v15.14.0/lib/node_modules/next/dist/server/require.js
- /Users/ken/.nvm/versions/node/v15.14.0/lib/node_modules/next/dist/server/next-server.js
- /Users/ken/.nvm/versions/node/v15.14.0/lib/node_modules/next/dist/server/next.js
- /Users/ken/.nvm/versions/node/v15.14.0/lib/node_modules/next/dist/server/lib/start-server.js
- /Users/ken/.nvm/versions/node/v15.14.0/lib/node_modules/next/dist/cli/next-dev.js
- /Users/ken/.nvm/versions/node/v15.14.0/lib/node_modules/next/dist/bin/next
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:924:15)
    at Function.mod._resolveFilename (/Users/ken/.nvm/versions/node/v15.14.0/lib/node_modules/next/dist/build/webpack/require-hook.js:182:28)
    at Function.Module._load (node:internal/modules/cjs/loader:769:27)
    at Module.require (node:internal/modules/cjs/loader:996:19)
    at require (node:internal/modules/cjs/helpers:92:18)
    at Object.../shared/lib/is-plain-object (/Users/ken/Documents/GitHub/blog_next/.next/server/pages/_document.js:175:18)
    at __webpack_require__ (/Users/ken/Documents/GitHub/blog_next/.next/server/webpack-runtime.js:33:42)
    at eval (webpack-internal:///../../../.nvm/versions/node/v15.14.0/lib/node_modules/next/dist/lib/is-error.js:7:22)
    at Object.../../../.nvm/versions/node/v15.14.0/lib/node_modules/next/dist/lib/is-error.js (/Users/ken/Documents/GitHub/blog_next/.next/server/pages/_document.js:77:1)
    at __webpack_require__ (/Users/ken/Documents/GitHub/blog_next/.next/server/webpack-runtime.js:33:42) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/Users/ken/Documents/GitHub/blog_next/.next/server/pages/_document.js',
    '/Users/ken/.nvm/versions/node/v15.14.0/lib/node_modules/next/dist/server/require.js',
    '/Users/ken/.nvm/versions/node/v15.14.0/lib/node_modules/next/dist/server/next-server.js',
    '/Users/ken/.nvm/versions/node/v15.14.0/lib/node_modules/next/dist/server/next.js',
    '/Users/ken/.nvm/versions/node/v15.14.0/lib/node_modules/next/dist/server/lib/start-server.js',
    '/Users/ken/.nvm/versions/node/v15.14.0/lib/node_modules/next/dist/cli/next-dev.js',
    '/Users/ken/.nvm/versions/node/v15.14.0/lib/node_modules/next/dist/bin/next'
  ]
}
Error: Cannot find module 'next/dist/shared/lib/is-plain-object.js'
Require stack:
- /Users/ken/Documents/GitHub/blog_next/.next/server/pages/_document.js
- /Users/ken/.nvm/versions/node/v15.14.0/lib/node_modules/next/dist/server/require.js
- /Users/ken/.nvm/versions/node/v15.14.0/lib/node_modules/next/dist/server/next-server.js
- /Users/ken/.nvm/versions/node/v15.14.0/lib/node_modules/next/dist/server/next.js
- /Users/ken/.nvm/versions/node/v15.14.0/lib/node_modules/next/dist/server/lib/start-server.js
- /Users/ken/.nvm/versions/node/v15.14.0/lib/node_modules/next/dist/cli/next-dev.js
- /Users/ken/.nvm/versions/node/v15.14.0/lib/node_modules/next/dist/bin/next
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:924:15)
    at Function.mod._resolveFilename (/Users/ken/.nvm/versions/node/v15.14.0/lib/node_modules/next/dist/build/webpack/require-hook.js:182:28)
    at Function.Module._load (node:internal/modules/cjs/loader:769:27)
    at Module.require (node:internal/modules/cjs/loader:996:19)
    at require (node:internal/modules/cjs/helpers:92:18)
    at Object.../shared/lib/is-plain-object (/Users/ken/Documents/GitHub/blog_next/.next/server/pages/_document.js:175:18)
    at __webpack_require__ (/Users/ken/Documents/GitHub/blog_next/.next/server/webpack-runtime.js:33:42)
    at eval (webpack-internal:///../../../.nvm/versions/node/v15.14.0/lib/node_modules/next/dist/lib/is-error.js:7:22)
    at Object.../../../.nvm/versions/node/v15.14.0/lib/node_modules/next/dist/lib/is-error.js (/Users/ken/Documents/GitHub/blog_next/.next/server/pages/_document.js:77:1)
    at __webpack_require__ (/Users/ken/Documents/GitHub/blog_next/.next/server/webpack-runtime.js:33:42) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/Users/ken/Documents/GitHub/blog_next/.next/server/pages/_document.js',
    '/Users/ken/.nvm/versions/node/v15.14.0/lib/node_modules/next/dist/server/require.js',
    '/Users/ken/.nvm/versions/node/v15.14.0/lib/node_modules/next/dist/server/next-server.js',
    '/Users/ken/.nvm/versions/node/v15.14.0/lib/node_modules/next/dist/server/next.js',
    '/Users/ken/.nvm/versions/node/v15.14.0/lib/node_modules/next/dist/server/lib/start-server.js',
    '/Users/ken/.nvm/versions/node/v15.14.0/lib/node_modules/next/dist/cli/next-dev.js',
    '/Users/ken/.nvm/versions/node/v15.14.0/lib/node_modules/next/dist/bin/next'
  ]
}```

**Comment by Pavitra554** [comment]
In my case its working...
`npx create-next-app --example blog my-blog`
or
`yarn create next-app --example blog my-blog`

then 
`npm i`
then 
`npm run dev`

than you can make a index.tsx and edit it css is already available. 
hope this helps @knbrlo

**Comment by nickdobos** [comment]
Running into this same issue. Template is un-usable, and won't compile :(.

**Comment by 1001Josias** [comment]
It is currently working without any problems here
